#spring config
spring:
  aop:
    auto: true
  datasource:
    name: smarttravel
    url: jdbc:mysql://localhost:3306/smarttravel
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: tyf950327
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 1000
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# MyBatis
mybatis:
  type-aliases-package: com.hrbeu.zzw.model
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#PageHelper
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
server:
  port: 8080
